### ISSUE TITLE
Splitting our issues/features into themes.

### ISSUE THREAD

**Issue by ColtonNash** [r2luna/cs160#17]
Lets set these in our theme columns. #1 being what we need right away, to #4 being features that still bring value but are less important.

**Comment by roberthd008** [comment]
I think I've got the User Stories organized/prioritized now.

**Comment by roberthd008** [comment]
Next should be the dev team assigning/estimating size to each.

**Comment by r2luna** [comment]
@roberthd008 we need more information about each issue to be able to the assigning/estimating.

**Comment by r2luna** [comment]
As the book says, each user story needs to have this kind of information:
![screen shot 2017-05-24 at 12 11 04 am](https://cloud.githubusercontent.com/assets/3915917/26389137/911b1384-4015-11e7-98e6-99c4a044842a.png)
